# Generated by Django 2.1.5 on 2019-01-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190105_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, '实战课'), (2, '免费课'), (0, '其它')], default=0, max_length=1, verbose_name='课程类型'),
        ),
    ]
